/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formulario;

/**
 *
 * @author HERNANDEZ
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setTitle("Sistema de Videojuego");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nmenu = new javax.swing.JMenuBar();
        nmCatalogo = new javax.swing.JMenu();
        mnuAddVideoGame = new javax.swing.JMenuItem();
        nmVenta = new javax.swing.JMenu();
        mnuRealizaVenta = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nmCatalogo.setText("Catalogo");

        mnuAddVideoGame.setText("Agregar Videojuego");
        mnuAddVideoGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAddVideoGameActionPerformed(evt);
            }
        });
        nmCatalogo.add(mnuAddVideoGame);

        nmenu.add(nmCatalogo);

        nmVenta.setText("Venta");

        mnuRealizaVenta.setText("Realizar Venta");
        mnuRealizaVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRealizaVentaActionPerformed(evt);
            }
        });
        nmVenta.add(mnuRealizaVenta);

        nmenu.add(nmVenta);

        setJMenuBar(nmenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuAddVideoGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAddVideoGameActionPerformed
        // TODO add your handling code here:
        frmVideoJuego objVJ = new frmVideoJuego();
        objVJ.setVisible(true);
    }//GEN-LAST:event_mnuAddVideoGameActionPerformed

    private void mnuRealizaVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRealizaVentaActionPerformed
        // TODO add your handling code here:
        frmVenta objVenta = new frmVenta();
        objVenta.setVisible(true);
    }//GEN-LAST:event_mnuRealizaVentaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem mnuAddVideoGame;
    private javax.swing.JMenuItem mnuRealizaVenta;
    private javax.swing.JMenu nmCatalogo;
    private javax.swing.JMenu nmVenta;
    private javax.swing.JMenuBar nmenu;
    // End of variables declaration//GEN-END:variables
}
